name: Linux

on:
  push:
  pull_request:

jobs:
  update-with-sudo:
    name: Linux with sudo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download go 1.19
        run: curl -OL https://go.dev/dl/go1.19.10.linux-amd64.tar.gz

      - name: Install go 1.19
        run: sudo tar -C /usr/local -xzf go1.19.10.linux-amd64.tar.gz

      - name: Add go into PATH
        run: echo /usr/local/go/bin >> $GITHUB_PATH

      - name: Check go version
        run: go version

      - name: Update go to latest version
        run: ./go-up.sh

      - name: Check latest go version
        run: go version

  update-without-sudo:
    name: Linux without sudo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download go 1.19
        run: curl -OL https://go.dev/dl/go1.19.10.linux-amd64.tar.gz

      - name: Install go 1.19
        run: mkdir -p ~/.local/opt && tar -C ~/.local/opt -xzf go1.19.10.linux-amd64.tar.gz

      - name: Add go into PATH
        run: echo ~/.local/opt/go/bin >> $GITHUB_PATH

      - name: Check go version
        run: go version

      - name: Update go to latest version
        run: ./go-up.sh

      - name: Check latest go version
        run: go version
